### ISSUE TITLE
Publish emit('watch') behavior to NPM

### ISSUE THREAD

**Issue by jeffomatic** [unbalanced/grunt-simple-watch#6]
Would you mind bumping the version once more so the watch events get emitted? This is a pretty useful feature for doing things like per-file recompiles.

**Comment by AMeng** [comment]
@unbalanced any chance you might push a new version to NPM?

**Comment by unbalanced** [comment]
updated, can you check now?

**Comment by AMeng** [comment]
:heart:

**Comment by unbalanced** [comment]
With pleasure!
Hope you love that plugin :+1: 

I actually don't use it by myself anymore (moved to contrib-watch)
